# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plugin.ui',
# licensing of 'plugin.ui' applies.
#
# Created: Sat May 25 12:32:56 2019
#      by: pyside2-uic  running on PySide2 5.12.3
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(272, 436)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mainLayout = QtWidgets.QVBoxLayout()
        self.mainLayout.setObjectName("mainLayout")
        self.topicLayout = QtWidgets.QFormLayout()
        self.topicLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.topicLayout.setObjectName("topicLayout")
        self.topicLbl = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        self.topicLbl.setFont(font)
        self.topicLbl.setObjectName("topicLbl")
        self.topicLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.topicLbl)
        self.topicCBox = QtWidgets.QComboBox(Form)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        self.topicCBox.setFont(font)
        self.topicCBox.setObjectName("topicCBox")
        self.topicCBox.addItem("")
        self.topicCBox.addItem("")
        self.topicCBox.addItem("")
        self.topicLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.topicCBox)
        self.mainLayout.addLayout(self.topicLayout)
        self.commentLayout = QtWidgets.QVBoxLayout()
        self.commentLayout.setObjectName("commentLayout")
        self.commentList = QtWidgets.QListWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commentList.sizePolicy().hasHeightForWidth())
        self.commentList.setSizePolicy(sizePolicy)
        self.commentList.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.commentList.setObjectName("commentList")
        QtWidgets.QListWidgetItem(self.commentList)
        self.commentLayout.addWidget(self.commentList)
        self.newCommentLayout = QtWidgets.QHBoxLayout()
        self.newCommentLayout.setObjectName("newCommentLayout")
        self.commentEdit = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commentEdit.sizePolicy().hasHeightForWidth())
        self.commentEdit.setSizePolicy(sizePolicy)
        self.commentEdit.setObjectName("commentEdit")
        self.newCommentLayout.addWidget(self.commentEdit)
        self.commentBtn = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commentBtn.sizePolicy().hasHeightForWidth())
        self.commentBtn.setSizePolicy(sizePolicy)
        self.commentBtn.setObjectName("commentBtn")
        self.newCommentLayout.addWidget(self.commentBtn)
        self.commentLayout.addLayout(self.newCommentLayout)
        self.mainLayout.addLayout(self.commentLayout)
        self.snapshotLayout = QtWidgets.QHBoxLayout()
        self.snapshotLayout.setObjectName("snapshotLayout")
        self.snapshotDisplay3 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.snapshotDisplay3.sizePolicy().hasHeightForWidth())
        self.snapshotDisplay3.setSizePolicy(sizePolicy)
        self.snapshotDisplay3.setMaximumSize(QtCore.QSize(16777215, 100))
        self.snapshotDisplay3.setStyleSheet("image: url(:/resources/snapshot2.jpg);")
        self.snapshotDisplay3.setText("")
        self.snapshotDisplay3.setObjectName("snapshotDisplay3")
        self.snapshotLayout.addWidget(self.snapshotDisplay3)
        self.snapshotDisplay2 = QtWidgets.QLabel(Form)
        self.snapshotDisplay2.setMaximumSize(QtCore.QSize(16777215, 200))
        self.snapshotDisplay2.setStyleSheet("\n"
"image: url(:/resources/snapshot1.jpg);\n"
"")
        self.snapshotDisplay2.setText("")
        self.snapshotDisplay2.setObjectName("snapshotDisplay2")
        self.snapshotLayout.addWidget(self.snapshotDisplay2)
        self.snapshotDisplay1 = QtWidgets.QLabel(Form)
        self.snapshotDisplay1.setMaximumSize(QtCore.QSize(16777215, 100))
        self.snapshotDisplay1.setStyleSheet("image: url(:/resources/snapshot3.png);")
        self.snapshotDisplay1.setText("")
        self.snapshotDisplay1.setObjectName("snapshotDisplay1")
        self.snapshotLayout.addWidget(self.snapshotDisplay1)
        self.mainLayout.addLayout(self.snapshotLayout)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        self.saveBtn = QtWidgets.QPushButton(Form)
        self.saveBtn.setObjectName("saveBtn")
        self.buttonLayout.addWidget(self.saveBtn)
        self.showBtn = QtWidgets.QPushButton(Form)
        self.showBtn.setObjectName("showBtn")
        self.buttonLayout.addWidget(self.showBtn)
        self.mainLayout.addLayout(self.buttonLayout)
        self.verticalLayout.addLayout(self.mainLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtWidgets.QApplication.translate("Form", "Form", None, -1))
        self.topicLbl.setText(QtWidgets.QApplication.translate("Form", "Topic", None, -1))
        self.topicCBox.setItemText(0, QtWidgets.QApplication.translate("Form", "Left wall is too short", None, -1))
        self.topicCBox.setItemText(1, QtWidgets.QApplication.translate("Form", "Remove windows", None, -1))
        self.topicCBox.setItemText(2, QtWidgets.QApplication.translate("Form", "Split room in two", None, -1))
        __sortingEnabled = self.commentList.isSortingEnabled()
        self.commentList.setSortingEnabled(False)
        self.commentList.setSortingEnabled(__sortingEnabled)
        self.commentEdit.setPlaceholderText(QtWidgets.QApplication.translate("Form", "New Comment", None, -1))
        self.commentBtn.setText(QtWidgets.QApplication.translate("Form", "Add", None, -1))
        self.saveBtn.setText(QtWidgets.QApplication.translate("Form", "Save", None, -1))
        self.showBtn.setText(QtWidgets.QApplication.translate("Form", "Show", None, -1))

import resources_rc
